server {
  listen       80;
  listen  [::]:80;
  server_name  localhost;

  location / {
    proxy_pass http://front-end;
  }

  location /core/api/v1 {
    proxy_pass http://core:8000;
  }
  
  location /map/api/artifacts {
    proxy_pass http://map:8080;
  }

  location /voting/api/polls {
    proxy_pass http://voting:8085;
  }

  location /email {
    proxy_pass http://email:8081;
  }
}